# Generated by Django 5.0.14 on 2026-03-08 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_bodega_movimientoinventario_inventariobodega'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Confirmada', 'Confirmada'), ('Anulada', 'Anulada')], default='Borrador', max_length=20)),
                ('procesada', models.BooleanField(default=False, editable=False)),
                ('cliente', models.ForeignKey(limit_choices_to={'es_cliente': True}, on_delete=django.db.models.deletion.PROTECT, to='terceros.tercero')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.item')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.facturaventa')),
            ],
        ),
    ]
