# Generated by Django 5.0.14 on 2026-05-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
