# Generated by Django 5.0.14 on 2026-05-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_facturaventa_anulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='cadena_qr',
            field=models.TextField(blank=True, null=True, verbose_name='Cadena QR'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='cufe',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='CUFE'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='dian_estado',
            field=models.CharField(choices=[('No Enviada', 'No Enviada'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='No Enviada', max_length=20, verbose_name='Estado DIAN'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='dian_fecha_validacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Validación DIAN'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='xml_dian',
            field=models.FileField(blank=True, null=True, upload_to='dian_xmls/', verbose_name='XML DIAN'),
        ),
    ]
