# Generated by Django 5.0.14 on 2026-05-29 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_correo_emision_empresa_smtp_password'),
        ('ventas', '0003_facturaventa_cadena_qr_facturaventa_cufe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolucionDIAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=5, verbose_name='Prefijo')),
                ('numero_inicial', models.IntegerField(verbose_name='Número Inicial')),
                ('numero_final', models.IntegerField(verbose_name='Número Final')),
                ('siguiente_numero', models.IntegerField(verbose_name='Siguiente Número')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('activa', models.BooleanField(default=True, verbose_name='Es Activa')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Resolución DIAN',
                'verbose_name_plural': 'Resoluciones DIAN',
            },
        ),
    ]
