# Generated by Django 5.0.14 on 2026-05-29 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_resoluciondian'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=20, unique=True, verbose_name='Número de Nota')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('motivo', models.TextField(default='Devolución de mercancía y anulación de factura', verbose_name='Motivo')),
                ('dian_estado', models.CharField(choices=[('No Enviada', 'No Enviada'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='No Enviada', max_length=20, verbose_name='Estado DIAN')),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='ventas.facturaventa', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Nota Crédito',
                'verbose_name_plural': 'Notas Crédito',
            },
        ),
    ]
