# Generated by Django 5.0.14 on 2026-03-07 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Kilogramo', max_length=100, verbose_name='Nombre')),
                ('abreviatura', models.CharField(help_text='Ej: kg', max_length=20, verbose_name='Abreviatura')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sku', models.CharField(max_length=50, unique=True, verbose_name='Código SKU')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Ítem')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras')),
                ('tipo_item', models.CharField(choices=[('Almacenable', 'Almacenable (Producto/Materia Prima)'), ('Consumible', 'Consumible (Insumo Menor)'), ('Servicio', 'Servicio (Intangible)'), ('Retal', 'Retal (Subproducto de Corte)')], max_length=30, verbose_name='Tipo de Ítem')),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Base')),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Promedio')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Porcentaje de IVA (%)')),
                ('maneja_inventario', models.BooleanField(default=True, verbose_name='Maneja Inventario')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoriaitem', verbose_name='Categoría')),
                ('unidad_medida_base', models.ForeignKey(help_text='La unidad mínima en la que se controla el stock', on_delete=django.db.models.deletion.PROTECT, to='inventario.unidadmedida', verbose_name='Unidad de Medida Base')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionUnidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_multiplicador', models.DecimalField(decimal_places=4, help_text='Ej: Si la unidad base es Kg y la alternativa es Tonelada, el factor es 1000', max_digits=10, verbose_name='Factor Multiplicador')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones', to='inventario.item', verbose_name='Ítem')),
                ('unidad_alternativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.unidadmedida', verbose_name='Unidad Alternativa')),
            ],
        ),
    ]
