# Generated by Django 5.0.14 on 2026-03-08 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('es_activa', models.BooleanField(default=True, verbose_name='Es Activa')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('Entrada', 'Entrada (Compra/Devolución)'), ('Salida', 'Salida (Venta/Merma)'), ('Traslado', 'Traslado entre Bodegas'), ('Ajuste', 'Ajuste de Inventario')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo al momento del movimiento', max_digits=12, verbose_name='Costo Unitario')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('concepto', models.CharField(help_text='Ej: Factura de Compra #123, Ajuste por gotera', max_length=255, verbose_name='Concepto')),
                ('bodega_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='inventario.bodega', verbose_name='Bodega Destino')),
                ('bodega_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='inventario.bodega', verbose_name='Bodega Origen')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.item', verbose_name='Ítem')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario (Kardex)',
                'verbose_name_plural': 'Movimientos de Inventario (Kardex)',
            },
        ),
        migrations.CreateModel(
            name='InventarioBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_actual', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='Cantidad Actual')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.bodega', verbose_name='Bodega')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.item', verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'Inventario por Bodega',
                'verbose_name_plural': 'Inventarios por Bodega',
                'unique_together': {('item', 'bodega')},
            },
        ),
    ]
