# Generated by Django 5.0.14 on 2026-05-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_bodega_movimientoinventario_inventariobodega'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventariobodega',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_actual__gte', 0)), name='inventario_cantidad_no_negativa'),
        ),
    ]
