# Generated by Django 5.0.14 on 2026-05-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventariobodega_inventario_cantidad_no_negativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=4, default=10, help_text='Cantidad mínima antes de generar alerta', max_digits=12, verbose_name='Stock Mínimo'),
        ),
    ]
