# Generated by Django 5.0.14 on 2026-03-08 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_bodega_movimientoinventario_inventariobodega'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Número de Orden (Lote)')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Finalizada', 'Finalizada (Mueve Inventario)')], default='Borrador', max_length=20)),
                ('procesada', models.BooleanField(default=False, editable=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InsumoConsumido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega')),
                ('item', models.ForeignKey(help_text='Materia Prima a consumir', on_delete=django.db.models.deletion.PROTECT, to='inventario.item')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='produccion.ordenproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('costo_unitario_asignado', models.DecimalField(decimal_places=2, help_text='Costo estimado por unidad tras la transformación', max_digits=12)),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega')),
                ('item', models.ForeignKey(help_text='Producto Terminado o Retal generado', on_delete=django.db.models.deletion.PROTECT, to='inventario.item')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='produccion.ordenproduccion')),
            ],
        ),
    ]
