# Generated by Django 5.0.14 on 2026-05-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='anulada',
            field=models.BooleanField(default=False),
        ),
    ]
