# Generated by Django 5.0.14 on 2026-05-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_ordenproduccion_anulada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('En Proceso', 'En Proceso (Planta)'), ('Finalizada', 'Finalizada (Mueve Inventario)')], default='Borrador', max_length=30),
        ),
    ]
