# Generated by Django 5.0.14 on 2026-03-03 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_cliente', models.BooleanField(default=False, verbose_name='Es Cliente')),
                ('es_proveedor', models.BooleanField(default=False, verbose_name='Es Proveedor')),
                ('es_empleado', models.BooleanField(default=False, verbose_name='Es Empleado')),
                ('tipo_documento', models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('Pasaporte', 'Pasaporte')], max_length=20, verbose_name='Tipo de Documento')),
                ('numero_identificacion', models.CharField(max_length=20, unique=True, verbose_name='Número de Identificación')),
                ('dv', models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito de Verificación (DV)')),
                ('tipo_persona', models.CharField(choices=[('Juridica', 'Jurídica'), ('Natural', 'Natural')], max_length=20, verbose_name='Tipo de Persona')),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razón Social')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('regimen_iva', models.CharField(choices=[('Responsable', 'Responsable de IVA'), ('No Responsable', 'No Responsable de IVA')], max_length=30, verbose_name='Régimen de IVA')),
                ('responsabilidades_fiscales', models.CharField(help_text='Ej: O-13, O-47', max_length=100, verbose_name='Responsabilidades Fiscales')),
                ('datos_completos', models.BooleanField(default=False, verbose_name='Datos Completos')),
                ('validacion_api_estado', models.CharField(choices=[('Validado', 'Validado'), ('Pendiente', 'Pendiente'), ('Desactualizado', 'Desactualizado')], default='Pendiente', max_length=30, verbose_name='Estado de Validación API')),
                ('fecha_ultima_validacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Última Validación')),
                ('requiere_atencion_contador', models.BooleanField(default=False, verbose_name='Requiere Atención Contador')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.municipio', verbose_name='Municipio')),
            ],
        ),
    ]
