# Generated by Django 5.0.14 on 2026-03-08 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_bodega_movimientoinventario_inventariobodega'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura_proveedor', models.CharField(max_length=50, verbose_name='Número de Factura del Proveedor')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Confirmada', 'Confirmada'), ('Anulada', 'Anulada')], default='Borrador', max_length=20, verbose_name='Estado')),
                ('proveedor', models.ForeignKey(limit_choices_to={'es_proveedor': True}, on_delete=django.db.models.deletion.PROTECT, to='terceros.tercero', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Subtotal')),
                ('bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega', verbose_name='Bodega de Destino')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.item', verbose_name='Ítem')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.facturacompra', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
            },
        ),
    ]
