# Generated by Django 5.0.14 on 2026-03-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='procesada',
            field=models.BooleanField(default=False, editable=False, help_text='Indica si la factura ya inyectó el stock al inventario'),
        ),
    ]
