# Generated by Django 5.0.14 on 2026-05-27 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_facturacompra_anulada'),
        ('inventario', '0002_bodega_movimientoinventario_inventariobodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='bodega_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.bodega', verbose_name='Bodega de Destino'),
        ),
    ]
