# Generated by Django 5.0.14 on 2026-05-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_detallecompra_bodega_destino'),
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together={('proveedor', 'numero_factura_proveedor')},
        ),
    ]
