# Generated by Django 5.0.14 on 2026-03-03 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCIIU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código CIIU')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(max_length=10, unique=True, verbose_name='Código DANE')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_dane', models.CharField(max_length=10, unique=True, verbose_name='Código DANE')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Municipio')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento', verbose_name='Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('dv', models.CharField(max_length=1, verbose_name='DV')),
                ('tipo_persona', models.CharField(choices=[('Juridica', 'Jurídica'), ('Natural', 'Natural')], max_length=20, verbose_name='Tipo de Persona')),
                ('regimen_iva', models.CharField(choices=[('Responsable', 'Responsable de IVA'), ('No Responsable', 'No Responsable de IVA')], max_length=30, verbose_name='Régimen de IVA')),
                ('responsabilidades_fiscales', models.CharField(help_text='Ej: O-13, O-47', max_length=100, verbose_name='Responsabilidades Fiscales')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('correo_facturacion', models.EmailField(max_length=254, verbose_name='Correo de Facturación')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('ciiu_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.actividadciiu', verbose_name='Actividad CIIU Principal')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.municipio', verbose_name='Municipio')),
            ],
        ),
    ]
