# Generated by Django 5.0.14 on 2026-05-28 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('Anulación', 'Anulación'), ('Creación', 'Creación'), ('Modificación', 'Modificación'), ('Pago', 'Pago')], max_length=30, verbose_name='Acción')),
                ('modulo', models.CharField(max_length=50, verbose_name='Módulo')),
                ('detalle', models.TextField(verbose_name='Detalle de la Operación')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
