# Generated by Django 5.0.14 on 2026-05-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correo_emision',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Emisión (SMTP)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Contraseña SMTP'),
        ),
    ]
