# Generated by Django 5.0.14 on 2026-05-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_correo_emision_empresa_smtp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='certificado_p12',
            field=models.FileField(blank=True, help_text='Certificado digital en formato .p12 o .pfx', null=True, upload_to='certificados_dian/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='clave_certificado',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='software_id_dian',
            field=models.CharField(blank=True, help_text='ID del Software Propio en la DIAN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='test_set_id_dian',
            field=models.CharField(blank=True, help_text='ID del Set de Pruebas de habilitación', max_length=100, null=True),
        ),
    ]
