# Generated by Django 5.0.14 on 2026-03-09 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_facturacompra_procesada'),
        ('terceros', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Bancolombia, Caja General', max_length=100)),
                ('tipo', models.CharField(choices=[('Banco', 'Banco'), ('Efectivo', 'Efectivo/Caja')], max_length=50)),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada')], default='Pendiente', editable=False, max_length=20)),
                ('cliente', models.ForeignKey(limit_choices_to={'es_cliente': True}, on_delete=django.db.models.deletion.PROTECT, to='terceros.tercero')),
                ('factura_origen', models.OneToOneField(help_text='Factura que genera la deuda', on_delete=django.db.models.deletion.PROTECT, to='ventas.facturaventa')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaPorPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada')], default='Pendiente', editable=False, max_length=20)),
                ('factura_origen', models.OneToOneField(help_text='Factura que genera la deuda', on_delete=django.db.models.deletion.PROTECT, to='compras.facturacompra')),
                ('proveedor', models.ForeignKey(limit_choices_to={'es_proveedor': True}, on_delete=django.db.models.deletion.PROTECT, to='terceros.tercero')),
            ],
        ),
        migrations.CreateModel(
            name='PagoEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('referencia', models.CharField(help_text='Ej: Cheque #987', max_length=100)),
                ('cuenta_origen', models.ForeignKey(help_text='De dónde salió la plata', on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuentabancaria')),
                ('cuenta_por_pagar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuentaporpagar')),
            ],
        ),
        migrations.CreateModel(
            name='PagoRecibido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('referencia', models.CharField(help_text='Ej: Transferencia #12345', max_length=100)),
                ('cuenta_destino', models.ForeignKey(help_text='A dónde entró la plata', on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuentabancaria')),
                ('cuenta_por_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuentaporcobrar')),
            ],
        ),
    ]
