# Generated by Django 5.0.14 on 2026-05-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesoreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentabancaria',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='entidad_bancaria',
            field=models.CharField(blank=True, help_text='Ej: Bancolombia, Banco de Bogotá', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='tipo_cuenta',
            field=models.CharField(choices=[('Ahorros', 'Ahorros'), ('Corriente', 'Corriente'), ('Efectivo', 'Efectivo/Caja')], default='Ahorros', max_length=50),
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='numero_cuenta',
            field=models.CharField(blank=True, help_text='Opcional para efectivo', max_length=50, null=True),
        ),
    ]
